### ISSUE TITLE
Panic with Nil Logging Fields

### ISSUE THREAD

**Issue by MrWako** [whuang8/redactrus#11]
Small issue, but Logrus accepts Nil logging fields and it turns out we have a few instances of this, usually logging an error that in some situations is nil. When adding redactus, the logging now panics in this situation.

I've created a small pull request and added a test to cover this here: https://github.com/whuang8/redactrus/pull/10 Would be great if you could consider merging this so that I can continue to use your original package rather than a fork.

Many thanks.

**Comment by whuang8** [comment]
https://github.com/whuang8/redactrus/pull/10 merged. Thanks again for the contribution!
